version: 2
updates:
- package-ecosystem: nuget
  directory: "/src/Radical.Windows.Presentation.CastleWindsor.Tests"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: release-2.0
- package-ecosystem: nuget
  directory: "/src/Radical.Windows.Presentation.CastleWindsor.Tests"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: master
- package-ecosystem: nuget
  directory: "/src/Radical.Windows.Presentation.CastleWindsor"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: master
- package-ecosystem: nuget
  directory: "/src/Radical.Windows.Presentation.CastleWindsor"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: release-2.0
- package-ecosystem: nuget
  directory: "/targets"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: master
- package-ecosystem: nuget
  directory: "/targets"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: release-2.0
