version: 1
update_configs:

# master
  - package_manager: "dotnet:nuget"
    directory: "/src/Radical.Windows.Presentation.CastleWindsor"
    update_schedule: "live"
    target_branch: master
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:patch"
  - package_manager: "dotnet:nuget"
    directory: "/src/Radical.Windows.Presentation.CastleWindsor.Tests"
    update_schedule: "live"
    target_branch: master
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"
  - package_manager: "dotnet:nuget"
    directory: "/targets"
    update_schedule: "live"
    target_branch: master
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"

# release-2.0
  - package_manager: "dotnet:nuget"
    directory: "/src/Radical.Windows.Presentation.CastleWindsor"
    update_schedule: "live"
    target_branch: release-2.0
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:patch"
  - package_manager: "dotnet:nuget"
    directory: "/src/Radical.Windows.Presentation.CastleWindsor.Tests"
    update_schedule: "live"
    target_branch: release-2.0
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"
  - package_manager: "dotnet:nuget"
    directory: "/targets"
    update_schedule: "live"
    target_branch: release-2.0
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"
